### ISSUE TITLE
Blended learning as base design criteria?

### ISSUE THREAD

**Issue by MarcelUntied** [stichtingsem/functional-overview#11]
Input Finance & Admin:
- Blended learning is more complex and because of that it can be the base design criteria and covers full digital and folio
- Digital and folio should be simpler and take less steps/actions (short cuts)

**Comment by benkoers** [comment]
yep: I would say base design is blended learning

**Comment by eliashassing154** [comment]
@MarcelUntied on the second point, you mean by treating them as two distinct product (parts) instead of one blended products?

**Comment by MarcelUntied** [comment]
@eliashassing154 No, that is not what we meant. Blended products (combi's) are more complex than a full digital product or a full folio product. If we can make a flow/process that works for blended products the other products should work also (and with fewer steps)

**Comment by wvholland** [comment]
> @eliashassing154 No, that is not what we meant. **Blended products (combi's) are more complex than a full digital product or a full folio product.** If we can make a flow/process that works for blended products the other products should work also (and with fewer steps)

@MarcelUntied I know that currently the blended products are more complex? Can you elaborate why that is in your opinion. Why is it not simple a stream of Folio and a stream of Digital that we treat in their own aspects ... is it because we treat the digital component in blended actually still as folio? (Just brain picking ...)

**Comment by eliashassing154** [comment]
Yes good question, I'm not sure what complexity you're referring to @MarcelUntied

**Comment by MarcelUntied** [comment]
@wvholland @eliashassing154 It is because of the fact the product has one EAN with a specific price (model). That is what makes it complex.

**Comment by HJTLN** [comment]
From a retail perspective: 1 EAN exists of multiple parts (e.g. a bed), which are on different locations in the warehouse and even can be delivered in parts (4 parts are on stock,  1 part will be delivered next day). We used a BOM (Bill of Materials) for that. Is that kind of solution applicable here?

**Comment by eliashassing154** [comment]
@MarcelUntied still not clear what that complexity is. Even is there 1 EAN for a blended product, why is that a problem in our use cases? Can we clarify by drawing it out?

**Comment by MarcelUntied** [comment]
@eliashassing154 Let's discuss it in the stream lead meeting and determine actions if necessary

**Comment by MarcelUntied** [comment]
@eliashassing154 @cliftonc In the stream lead we discussed this issue.

Outcome: This issue will be discussed in all the work streams this week. The results will be discussed in the next stream lead meeting

**Comment by MarcelUntied** [comment]
https://github.com/stichtingsem/functional-overview/blob/master/proposed-decisions.md
