### ISSUE TITLE
Full Digital: Sales invoice on usage?

### ISSUE THREAD

**Issue by MarcelUntied** [stichtingsem/functional-overview#12]
Input work stream finance & admin:
- No right of return after access/first usage
- The process from entitlement to usage should be traceable and transparent so partners in the ecosystem can determine their own way of delivery and invoicing

**Comment by wvholland** [comment]
see also my point [here](https://github.com/stichtingsem/functional-overview/issues/13#issuecomment-646030435)

**Comment by wvholland** [comment]
on transparency .. hmmm .. between the parties involved for sure ...

**Comment by cliftonc** [comment]
I think this is where a conversation about granularity of licensing is perhaps connected.

We discussed in track 3 a principle of `license at the highest level` - so try and avoid attaching a license to a named individual, unless its purchased by that person specifically (e.g. some of the vocational education examples).  

This is however something that is dealt with internally within the Learning Application - each of those providers need to decide if they want to allow this model commercially - it is effectively moving from named user to active user licensing.

If this is possible, the upside is that it will make the end to end much more reliable for a school, as moving students between classes will have zero administration impact.

**Comment by MarcelUntied** [comment]
@cliftonc I think we have to look in to this in more detail. Because the user does order confirmation (UC 3.0) on a user level this will be converted to a order on individual level at the market place. The market place updates the LMS and LA on school level and/or individual level?

**Comment by HJTLN** [comment]
referring to oculus here as well as I did here #13 : https://support.oculus.com/964479930393572/#:~:text=You%20may%20return%20apps%2C%20games,no%20more%20than%20two%20hours.

**Comment by MarcelUntied** [comment]
https://github.com/stichtingsem/functional-overview/blob/master/proposed-decisions.md
