### ISSUE TITLE
Blended/Folio: Sales invoice on delivery of physical component?

### ISSUE THREAD

**Issue by MarcelUntied** [stichtingsem/functional-overview#13]
Input work stream finance & Admin:
- Due to tax and auditing rules invoicing of blended and folio products has to take place after delivery of the physical component
- Can digital component be available for delivery of physical component? (Discussion)
If so what is the base for invoicing? Between buyer and market place and between market place and learning application?

**Comment by wvholland** [comment]
NIce discussion in the Educational context ;-)
Discussion on folio I can understand. Perhaps some web shop ruling might be effictive (no clue in education or in Tender - like 30 days right to return ... and do you need to wait for revenue recognition)

On digital, the 'normal' (read everywhere else) rule is that the moment you can guarentee that the user can access the material (so url + license key) then you are allowed to assume it can be used and you can recognize the revenue ... (besides webshop ruling).

But we are dealing with education where the usage is sometimes many months later in SE than the moment of buying/selecting. The revenue recognition needs to be part of the commercial agreement between MP and LA (all kind of variants might exist there, once chosen is bought, till you are allowed to try it for 3 times/weeks, before we are sure it will be invoiced (sorry read entitlement will be trasformed into cash flow)

**Comment by wvholland** [comment]
On blended I have no clue... what the rules and regulations are the moment you shrink wrap folio and digital .. (how to shrinkwrap digital ... adding URL and license key with the book perhaps, then see above on revenue recogition )

**Comment by MarcelUntied** [comment]
@wvholland Thanks for your insights. We were looking for the boundaries between legislation and the wish from schools and parents to only pay for things that are used.

Outcome in the work stream was transparency between the partners in the Ecosystem over the process from **order confirmation > entitlement > delivery/usage** (pre-competitive). The partners will have to define their own way of work/proposition on the defined services (competitive).

**Comment by cliftonc** [comment]
From a digital perspective there should be no issue with all the information about the selection being provided early, but with a future start date for the digital product.  If it was purely digital then any revenue recognition would begin at that date.

I agree with @wvholland that we probably need an accountant to clarify what happens in a blended product if there are different delivery dates for the components, and how that revenue can be recognised.

**Comment by MarcelUntied** [comment]
@cliftonc Simon van Huffelen in my work stream is an accountant. I will discuss it within my work stream

**Comment by HJTLN** [comment]
To add some new perspectives: at Oculus, you can buy a game (digitally), download it play it for some time and if it is not of your liking and your progress/ playtime is within given boundaries, you still can return the game en get refunded:
https://support.oculus.com/964479930393572/#:~:text=You%20may%20return%20apps%2C%20games,no%20more%20than%20two%20hours.

**Comment by MarcelUntied** [comment]
https://github.com/stichtingsem/functional-overview/blob/master/proposed-decisions.md
