### ISSUE TITLE
Should we bring SIS (LAS) in sync with LML (at front)?

### ISSUE THREAD

**Issue by MarcelUntied** [stichtingsem/functional-overview#15]
Input work stream:
- School structure (SIS) available in LML? (discussion)
- Additional service? (technical)
- School structure contains the following entities: school, location, pupils, teacher, groups, subjects
- Which entities/data of the SIS (LAS) should be available to MP, LA, SA? (functional)
- School is in control of the accessibility to the entities/data within SIS
- Target binding based on role > minimize data > Example: prognosis based on pupils SIS available to MP

**Comment by cliftonc** [comment]
Some comments:

- We had envisaged that the Marketplace would connect to the SIS to get the school, location, groups, subjects info (not teacher and pupil) to enable efficient creation of the LML.
- Definitely agree with minimisation of data transfer, though we should explore using mechanisms where each participant explains what data they need access to (like adding a 3rd party application to your facebook or google account, where it explicitly requests access to certain entities with a reason, and the administrator approves it).
- Some Learning Applications will need more data than others, as they may provide more sophisticated tools - we want to enable this to happen vs constrain it (and drive the creation of manual back doors), but keep the school in control at all times.

**Comment by wvholland** [comment]
Just for sake of discussion: Imho I can envision that in an early stage the LA only needs to know the expected number of 'usage' in order to scale the content on the right place (or even earlier only which content will be used) .. in case of the rough numbers it would simple help if the SIS could provide in the LML provided to the LA the bold figure numbers. Later on in the process these numbers become more and more precise. The moment the LML is linked in the LMS, more precise numbers can be provided based on actual info in the SIS.

**Comment by MarcelUntied** [comment]
@wvholland To make things clear. Your comment is on the example in the last bullet? This was only a part of the discussion in the work stream finance & admin, We think that a sync of the school structure between SIS and LML at front can reduce (delivery) errors and related repairs

**Comment by wvholland** [comment]
> @wvholland To make things clear. Your comment is on the example in the last bullet? This was only a part of the discussion in the work stream finance & admin, We think that a sync of the school structure between SIS and LML at front can reduce (delivery) errors and related repairs

My comment was in general not only on the last bullet. We (@cliftonc, Albert and I) in general believed that more transparency will avoid errors. On the other hand in SE with the 'current' way of working the LML can be acurate with SIS data on the moment of publishing of the LML (May/June) but not anymore on the moment of shipping (July/August) or usage (Sept-July)

**Comment by HJTLN** [comment]
For my perception (as was stated in the kickoff, to use existing integration where possible): are most bullets covered by the possibilities offered by (one of the profiles of)UWLR?

**Comment by MarcelUntied** [comment]
@HJTLN The main difference between UWLR-FDE and this possible additional service is that SIS and LML are synced (school structure) at an earlier phase (determine LML) in the process. UWLR-FDE processes transaction data from SIS to market place after the LML is finalized.

**Comment by erikdikkers** [comment]
Whether UWLR-FDE is sufficiënt enough or not is yet to be determined. I won't call it an _existing integration_ yet. This season will be the first time UWRL-FDE will be used and not all SIS support it.

If there will be an additional service to sync from SIS to Marketplace I suggest a new format to be determind by the technical track to cover both phases at once. Let's not define two seperate integrations.

**Comment by MarcelUntied** [comment]
https://github.com/stichtingsem/functional-overview/blob/master/proposed-decisions.md
