### ISSUE TITLE
Data reliability and integrity

### ISSUE THREAD

**Issue by MarcelUntied** [stichtingsem/functional-overview#16]
Input work stream finance & Admin:

**Principles:**

First Time Right > Avoidance of errors and repairs

**Discussion point**

Access Rights > No distributor filters in licenses/access links?

**Comment by wvholland** [comment]
> Input work stream finance & Admin:
> 
> **Principles:**
> 
> First Time Right > Avoidance of errors and repairs
> 
> **Discussion point**
> 
> Access Rights > No distributor filters in licenses/access links?

Can you elaborate a bit here because it's hard to contribute now ...

**Comment by cliftonc** [comment]
> Access Rights > No distributor filters in licenses/access links?

We discussed in an earlier stage that the ambition here should be that all links are 'dumb', and that the context required on the Learning Application would be obtained via:

- Information from the IdP to identify the user, their user type and their school
- Information from the SIS (so it can understand which classes, groups, subjects the user belongs to in that school)

If both of the above are valid, the link to an application in the LMS can simply be a link with _no user identifying information at all_, it should only contain information relative to the correct start point of the Learning Application (e.g. the front door for a specific product, or a specific section, quiz, assignment etc.) and the pointer to which IdP to use to identify them.

Given that the Marketplace has previously provided information on what the school has selected directly to the LA, it will also have context over which Marketplace (in most scenarios provided by a distributor) the school used to select the products - no need for this information to be in a link.

**Comment by HJTLN** [comment]
For data reliablity at a max level, there should be a single source of truth. Every additional source/ update possibility will lower the reliability.
So:
**what is the purpose this issue is aiming for?** 
and
 **Why are these two questions in 1 issue, because both can, from a data perspective, be attained in different ways?**

**Comment by MarcelUntied** [comment]
@wvholland @HJTLN 

There is one principle (**First Time Right**) we would like to add to the list of principles from the technical work stream. @cliftonc 

The other (**Access Rights**) is a discussion point. In the current chain the license services has the possibility to filter licenses on the distributor that sold the license. Example: This means that Iddink can not see the licenses bought at TLN.

We want to discuss if this is stil desireable in the new Ecosystem

**Comment by HJTLN** [comment]
"There is one principle (First Time Right)"

Question remains: does First Time Right add to reliability en integrity of data? --> 3 data sources giving 'same' data (with minor delta's) first time right...what is the correct data in that case?

**Comment by MarcelUntied** [comment]
@HJTLN First time right is only possible if data (LML, user, school) is reliable and integer before a transaction takes place. A change in data (e.g. subject change) in data source(s) leads to adjustment(s) of the transaction, but is fully traceable (transparent) for the involved partners in the Ecosystem

So First Time Right focuses on the quality (integrity and reliability) of stem data

**Comment by MarcelUntied** [comment]
https://github.com/stichtingsem/functional-overview/blob/master/proposed-decisions.md
