### ISSUE TITLE
What is 'In Scope'?

### ISSUE THREAD

**Issue by MarcelUntied** [stichtingsem/functional-overview#17]
- VO (secondary) and MBO (vocational)
- Full Digital (100% digital)
- Blended (combi’s)
- Folio (incl. paper vouchers): Partners (SA, MP) within the eco-system have to evaluate the impact of the proposed solutions on their supply chain (forecasts/prognosis, purchase, stock, etc)
- Returns
- Return reasons: Changes LML (school), Mutations SIS (change of subjects, OKO)
- ECK & NON ECK?

**Comment by benkoers** [comment]
in my perspective: (but lets chek it in the steering committee
Both  VO/MBO; blended, lifo, fully digital and folio; 
First to do the happy flow and then the exceptions including the return-process
focus on ECK and see non-ECK as exception

**Comment by eliashassing154** [comment]
I don't see how lifo is different from blended @benkoers ? Agree on the non ECK as exception. @MarcelUntied are you creating a use case for returns?

**Comment by MarcelUntied** [comment]
@eliashassing154 I think we should determine if returns are in scope for the coming weeks. If that is the case I/we could make a use case for returns, but it is not according to the proposed approach of work stream finance and admin. Let's discuss this in our stream lead session

**Comment by wvholland** [comment]
I assume (and that is always wrong ... that's why I ask explicit) that when we are talking about returns we are talking on folio stuff?

**Comment by eliashassing154** [comment]
OK, let's do that @MarcelUntied

**Comment by eliashassing154** [comment]
@wvholland great question - I'm assuming the same

**Comment by HJTLN** [comment]
> I assume (and that is always wrong ... that's why I ask explicit) that when we are talking about returns we are talking on folio stuff?

Why only folio, as for digital returns are possible too (even cancellation) however, both should be separated from the happy flow, nonetheless *not* be forgotten

**Comment by MarcelUntied** [comment]
@eliashassing154 @wvholland I think your assumption must be validated. If digital is invoiced after first access/usage you are right, but with blended constructions and/or non administrated pupils/usres (**non happy flow > out of scope for now**) this is not always the case.

Example: User buys a blended product (or LIFO). Folio component is delivered and digital component is not used. Pupil/user decides to return the folio part. In that case the entitlement should be reversed.

**Comment by MarcelUntied** [comment]
https://github.com/stichtingsem/functional-overview/blob/master/proposed-decisions.md
