### ISSUE TITLE
Will the Learning Application send usage information for blended products?

### ISSUE THREAD

**Issue by MarcelUntied** [stichtingsem/functional-overview#20]

**Comment by cliftonc** [comment]
I can speak for earlier conversations within the CTO group, and some principals / topics that were discussed there are important:

- We should always have the source system send data, not pass it on via an intermediary.
- The LMS does have a view of usage information, but it won't be complete.  What is captured there are clicks on the link to a product, not actual usage.
- The LMS could send this information back to the marketplace (or present it to users), and it can be triangulated with information from the LP to give a complete picture.
- But in this case real usage is data that is provided to the ecosystem by the LP, so it is proposed this be the source for anything related to billing in post pay type models.

**Comment by MarcelUntied** [comment]
My bad. I meant LA/LP instead of LMS. I've changed the title of the issue

**Comment by wvholland** [comment]
@MarcelUntied please avoid unneccesary new abbreviations. Or what is the purpose of LP vs LA (Learning Application)?

**Comment by wvholland** [comment]
Just to be sure, Or to clarify, what do you mean with blended products (imho combination of Folio and Digital)? In the latter case, the LA will absolutely send usage/user information on digital content to either the Market Place (kind of yes there has indeed been usage on this digital content - needed for entitlement and contract things), And results also need to be shared with the LMS (results might also be, student did finish the test on paragraph 4.2) so that the LMS can update the 'Studiewijzer'

**Comment by wvholland** [comment]
On folio all these things are more difficult - ;-) even for parents to know if the pupil opened the books .. Both LA as LMS have hardly any (or even none) knowledge on this

**Comment by MarcelUntied** [comment]
@wvholland I meant the combination of Folio and Digital (In dutch: combi's). In the work stream finance and admin we are discussing the possibility for the digital component to be available before delivery of the physical component. In that case the usage information can be crucial for invoicing and returns

**Comment by MarcelUntied** [comment]
@wvholland If LMS or LA had knowledge of use of Folio content, it would be a case of 'Big Brother is watching you' ;-)

**Comment by benkoers** [comment]
I'll agree with Winfried and was also a discussion in the functional track: there are two kinds of information that should come back from the digital learning material form the LA:  User-information (results/progress; mostly send to the LMS) and usage-information (mostly send to SIS/LMS and Marketplace for different reasons

**Comment by erikdikkers** [comment]
The split between the two kinds of information (user-information vs usage-information) is crucial and makes it clear. I suggest to add this split of information to the glossary.

**Comment by MarcelUntied** [comment]
https://github.com/stichtingsem/functional-overview/blob/master/proposed-decisions.md
